Feature/1 setting view
DeveloperAcademy-POSTECH/MC3-Team6-Hakenruruco pull request #10
Opened 2022-07-18 02:06 UTC by obtusa07

## 개요
테이블 뷰를 만들기 위해 필요한 Cell과 SettingViewController 기본 구조 생성 및 sceneDelegate 코드 수정

## 작업사항 
### 작업 사항

프로필 화면에서 심볼과 이름 그리고 테이블 뷰로 원하는 요소를 출력하는 것까지 구현했습니다.
UI만 구성하여 그렸으며 기능은 없습니다.

### References
ex) 작업시 참고한 자료가 있다면 추가해주세요!
  - [Auto Layout](https://ios-development.tistory.com/67?category=892896)
  - [TableView](https://eastroot1590.tistory.com/entry/IOS-Beginner-UITableView-tutorial-dynamic-height)

### 테스트 결과
<img width="950" alt="image" src="https://user-images.githubusercontent.com/47441965/179435187-02629152-4e4a-4501-906f-4dec21a17c7a.png">

## 그외
### 리뷰 포인트 
- 이상한, 불필요한, 중복 코드 선언

### 진행 예정 사항
ex) 작업 진행 예정사항 및 개선하고 싶은 내용이 있다면 추가 해주세요 
- [ ] 현재 Section 분류를 어떻게 해야할지 코드 구조를 고민중입니다.
- [ ] 네비게이션 기능을 부여하여 각 테이블 셀에서 해당하는 페이지로 이동 할 수 있어야 합니다.
- [ ] 6개의 셀마다 뷰가 존재하여 기능을 수행해야 합니다.

2022-07-18 09:58 UTC, cozytk requested changes
고생하셨습니다!!!!!!

2022-07-18 09:58 UTC, cozytk commented on TodayAnbu/Sources/Controllers/ViewController.swift
>          print("sdsdsdsdss")
# Request
불필요한 print문은 지워주세요!

2022-07-18 09:58 UTC, cozytk commented on TodayAnbu/Sources/Controllers/SettingViewController.swift
> +        NSLayoutConstraint.activate([
#  Comment
가르침 잘 써먹겠습니다 ㅎㅎㅎ

2022-07-18 09:58 UTC, cozytk commented on TodayAnbu/Sources/Models/SettingHeaderView.swift
> +    }
# Comment
이 부분도 가르침 주신 `NSLayoutConstraint` 를 활용하여 통일성 있게 코드를 짜면 더 좋을 것 같슴다 ㅎㅎㅎ

2022-07-18 09:58 UTC, cozytk commented on TodayAnbu/Sources/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
# Request
SceneDelegate는 SettingView로 시작하지 않기때문에 `develop` 에 합치려면 수정필요할거같아요~

2022-07-19 02:26 UTC, obtusa07 reviewed
감사감사 ㅎㅎㅎ

2022-07-19 02:26 UTC, obtusa07 commented on TodayAnbu/Sources/Controllers/ViewController.swift
>          print("sdsdsdsdss")
지웠습니다!

2022-07-19 02:26 UTC, obtusa07 commented on TodayAnbu/Sources/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
앞으로 개발에 용이하게 주석처리 했습니다.

2022-07-19 02:35 UTC, Kim-Yeon-ho approved these changes
구두 합의

2022-07-19 02:37 UTC, cozytk approved these changes
고생하숐쑴다

2022-07-19 02:37 UTC, merged